name: Build and Package Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest # 或者ubuntu-latest, macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.1' # 指定Python版本

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Package Application
      run: pyinstaller --onefile --windowed --icon=favicon.ico temp.py

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: packaged-app
        path: dist/
